### ISSUE TITLE
Allow a more global style of middleware

### ISSUE THREAD

**Issue by wezzle** [NYTimes/gizmo#129]
Hi,

When trying to implement a CORS handler that catches all OPTIONS requests I noticed that the current Middleware wraps all requests that are defined in the Endpoints function. Would it be possible to allow wrapping of the [mux.ServeHTTP func](https://github.com/NYTimes/gizmo/blob/12c3a2a0a5dcc7cdc6f3d13b1ceae135872f786a/server/simple_server.go#L101) somehow?

When using httprouter instead of Gorilla at least the OPTIONS requests are handled by the router itself but there is no way of adding allowed origins to that response.

Prehaps a RouterMiddleware function that allows you to wrap the mux's ServeHTTP.

What are your thoughts on this?

**Comment by jprobinson** [comment]
Howdy @wezzle! Sorry for the delay, I've been on vacation.

This has been a pain for us in the past as well. Historically, folks have just created an additional 'OPTIONS' handler for each endpoint that requires CORS, but it's definitely not the most satisfying resolution. 

One solution could be to wrap the existing `Middleware` around the `mux.ServeHTTP` instead of chaining it below in the SimpleServer's `Register` method. That sounds like a possibility, but I haven't thought very much on it to see if there would be any unintended consequences.

If you're interested in putting a PR together to try it out, I'm definitely interested.
