### ISSUE TITLE
`kit.LogErrorMsg` does not wrap log message in `Error` level

### ISSUE THREAD

**Issue by jamesaspence** [nytimes/gizmo#200]
When logging using `kit.LogErrorMsg`, the type is set to `error` but the level is not set.

Could we wrap this call like so?
```
return level.Error(kit.Logger(ctx)).log("error", err, "message", message)
```

In a related note - it'd be nice to have a few other convenience funcs like `LogDebugMsg`, `LogInfoMsg`, `LogWarnMsg`, etc. that could work the same way.

**Comment by jprobinson** [comment]
Instead of  `LogDebugMsg`, I'd be fine with perhaps making `LogMsg` an "info" or "debug" level log by default as it's set up to not pass anything more than a simple informational message with no other values.

In the same vein, I've found myself often abusing the `Msg` fields to look like: `kit.LogMsg(ctx, fmt.Sprintf("bad blah: %#v", bleh))`,  which is a bad habit as we should be using structured logging properly to pass information.

To push folks away from using using the "message" field for the kitchen sink, I wonder if we should expose the additional funcs like `kit.ErrorLogger(ctx).Log("message", "bad blah", "blah", bleh)` instead?

Another thought, if we want to cut out the use of the magic "message" key above, we could make a `func WithMsg(log.Logger, string) log.Logger` function? Seems a bit builder-pattern-y to me, but could work?
